services:  
  backend:
    build: ./backend
    container_name: "${PROJECT_NAME}_backend"
    command: "gunicorn backend.wsgi:application --bind 0.0.0.0:${BACKEND_PORT}"
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: ${BACKEND_PORT} 
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
    env_file:
      - .env.prod
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    container_name: "${PROJECT_NAME}_postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    restart: always  

  frontend:
    build:
      context: ./frontend
    container_name: "${PROJECT_NAME}_frontend"
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
